defmodule Configuration do
  @songs_db [
    # Drill EP, Creep, Anyone Can Play Guitar
    %{"artist" => "Radiohead", "title" => "Stupid Car"},
    %{"artist" => "Radiohead", "title" => "Inside My Head"},
    %{"artist" => "Radiohead", "title" => "Million Dollar Question"},
    %{"artist" => "Radiohead", "title" => "Yes I Am"},
    %{"artist" => "Radiohead", "title" => "Faithless the Wonder Boy"},
    %{"artist" => "Radiohead", "title" => "Coke Babies"},
    %{"artist" => "Radiohead", "title" => "Pop Is Dead"},
    # Pablo Honey
    %{"artist" => "Radiohead", "title" => "You"},
    %{"artist" => "Radiohead", "title" => "Creep"},
    %{"artist" => "Radiohead", "title" => "How Do You?"},
    %{"artist" => "Radiohead", "title" => "Stop Whispering"},
    %{"artist" => "Radiohead", "title" => "Thinking About You"},
    %{"artist" => "Radiohead", "title" => "Anyone Can Play Guitar"},
    %{"artist" => "Radiohead", "title" => "Ripcord"},
    %{"artist" => "Radiohead", "title" => "Vegetable"},
    %{"artist" => "Radiohead", "title" => "Prove Yourself"},
    %{"artist" => "Radiohead", "title" => "I Can't"},
    %{"artist" => "Radiohead", "title" => "Lurgee"},
    %{"artist" => "Radiohead", "title" => "Blow Out"},
    # My Iron Lung, High & Dry / Planet Telex
    %{"artist" => "Radiohead", "title" => "The Trickster"},
    %{"artist" => "Radiohead", "title" => "Lewis - Mistreated"},
    %{"artist" => "Radiohead", "title" => "Punchdrunk Lovesick Singalong"},
    %{"artist" => "Radiohead", "title" => "Permanent Daylight"},
    %{"artist" => "Radiohead", "title" => "Lozenge of Love"},
    %{"artist" => "Radiohead", "title" => "You Never Wash Up After Yourself"},
    %{"artist" => "Radiohead", "title" => "Maquiladora"},
    %{"artist" => "Radiohead", "title" => "Killer Cars"},
    # The Bends
    %{"artist" => "Radiohead", "title" => "Planet Telex"},
    %{"artist" => "Radiohead", "title" => "The Bends"},
    %{"artist" => "Radiohead", "title" => "High and Dry"},
    %{"artist" => "Radiohead", "title" => "Fake Plastic Trees"},
    %{"artist" => "Radiohead", "title" => "Bones"},
    %{"artist" => "Radiohead", "title" => "(Nice Dream)"},
    %{"artist" => "Radiohead", "title" => "Just"},
    %{"artist" => "Radiohead", "title" => "My Iron Lung"},
    %{"artist" => "Radiohead", "title" => "Bullet Proof..I Wish I Was"},
    %{"artist" => "Radiohead", "title" => "Black Star"},
    %{"artist" => "Radiohead", "title" => "Sulk"},
    %{"artist" => "Radiohead", "title" => "Street Spirit (Fade Out)"},
    # Fake Plastic Trees, Just, Street Spirit (Fade Out)
    %{"artist" => "Radiohead", "title" => "India Rubber"},
    %{"artist" => "Radiohead", "title" => "How Can You Be Sure?"},
    %{"artist" => "Radiohead", "title" => "Talk Show Host"},
    %{"artist" => "Radiohead", "title" => "Bishop's Robes"},
    %{"artist" => "Radiohead", "title" => "Banana Co."},
    %{"artist" => "Radiohead", "title" => "Molasses"},
    # Paranoid Android
    %{"artist" => "Radiohead", "title" => "Polyethylene (Parts 1 & 2)"},
    %{"artist" => "Radiohead", "title" => "Pearly*"},
    %{"artist" => "Radiohead", "title" => "A Reminder"},
    %{"artist" => "Radiohead", "title" => "Melatonin"},
    # OK Computer
    %{"artist" => "Radiohead", "title" => "Airbag"},
    %{"artist" => "Radiohead", "title" => "Paranoid Android"},
    %{"artist" => "Radiohead", "title" => "Subterranean Homesick Alien"},
    %{"artist" => "Radiohead", "title" => "Exit Music (For a Film)"},
    %{"artist" => "Radiohead", "title" => "Let Down"},
    %{"artist" => "Radiohead", "title" => "Karma Police"},
    %{"artist" => "Radiohead", "title" => "Fitter Happier"},
    %{"artist" => "Radiohead", "title" => "Electioneering"},
    %{"artist" => "Radiohead", "title" => "Climbing Up the Walls"},
    %{"artist" => "Radiohead", "title" => "No Surprises"},
    %{"artist" => "Radiohead", "title" => "Lucky"},
    %{"artist" => "Radiohead", "title" => "The Tourist"},
    # Karma Police, No Surprises
    %{"artist" => "Radiohead", "title" => "Meeting in the Aisle"},
    %{"artist" => "Radiohead", "title" => "Lull"},
    %{"artist" => "Radiohead", "title" => "Palo Alto"},
    %{"artist" => "Radiohead", "title" => "How I Made My Millions"},
    # Kid A
    %{"artist" => "Radiohead", "title" => "Everything in Its Right Place"},
    %{"artist" => "Radiohead", "title" => "Kid A"},
    %{"artist" => "Radiohead", "title" => "The National Anthem"},
    %{"artist" => "Radiohead", "title" => "How to Disappear Completely"},
    %{"artist" => "Radiohead", "title" => "Treefingers"},
    %{"artist" => "Radiohead", "title" => "Optimistic"},
    %{"artist" => "Radiohead", "title" => "In Limbo"},
    %{"artist" => "Radiohead", "title" => "Idioteque"},
    %{"artist" => "Radiohead", "title" => "Morning Bell"},
    %{"artist" => "Radiohead", "title" => "Motion Picture Soundtrack"},
    # Amnesiac
    %{"artist" => "Radiohead", "title" => "Packt Like Sardines in a Crushd Tin Box"},
    %{"artist" => "Radiohead", "title" => "Pyramid Song"},
    %{"artist" => "Radiohead", "title" => "Pulk/Pull Revolving Doors"},
    %{"artist" => "Radiohead", "title" => "You and Whose Army?"},
    %{"artist" => "Radiohead", "title" => "I Might Be Wrong"},
    %{"artist" => "Radiohead", "title" => "Knives Out"},
    %{"artist" => "Radiohead", "title" => "Morning Bell/Amnesiac"},
    %{"artist" => "Radiohead", "title" => "Dollars and Cents"},
    %{"artist" => "Radiohead", "title" => "Hunting Bears"},
    %{"artist" => "Radiohead", "title" => "Like Spinning Plates"},
    %{"artist" => "Radiohead", "title" => "Life in a Glasshouse"},
    # Pyramid Song, Knives Out
    %{"artist" => "Radiohead", "title" => "The Amazing Sounds of Orgy"},
    %{"artist" => "Radiohead", "title" => "Trans-Atlantic Drawl"},
    %{"artist" => "Radiohead", "title" => "Fast-Track"},
    %{"artist" => "Radiohead", "title" => "Kinetic"},
    %{"artist" => "Radiohead", "title" => "Cuttooth"},
    %{"artist" => "Radiohead", "title" => "Worrywort"},
    %{"artist" => "Radiohead", "title" => "Fog"},
    # Hail to the Thief
    %{"artist" => "Radiohead", "title" => "2 + 2 = 5"},
    %{"artist" => "Radiohead", "title" => "Sit Down. Stand Up."},
    %{"artist" => "Radiohead", "title" => "Sail to the Moon"},
    %{"artist" => "Radiohead", "title" => "Backdrifts"},
    %{"artist" => "Radiohead", "title" => "Go to Sleep"},
    %{"artist" => "Radiohead", "title" => "Where I End and You Begin"},
    %{"artist" => "Radiohead", "title" => "We Suck Young Blood"},
    %{"artist" => "Radiohead", "title" => "The Gloaming"},
    %{"artist" => "Radiohead", "title" => "There There"},
    %{"artist" => "Radiohead", "title" => "I Will"},
    %{"artist" => "Radiohead", "title" => "A Punchup at a Wedding"},
    %{"artist" => "Radiohead", "title" => "Myxomatosis"},
    %{"artist" => "Radiohead", "title" => "Scatterbrain"},
    %{"artist" => "Radiohead", "title" => "A Wolf at the Door"},
    # Com Lag=> 2+2=5
    %{"artist" => "Radiohead", "title" => "Paperbag Writer"},
    %{"artist" => "Radiohead", "title" => "I Am a Wicked Child"},
    %{"artist" => "Radiohead", "title" => "I Am Citizen Insane"},
    %{"artist" => "Radiohead", "title" => "Gagging Order"},
    %{"artist" => "Radiohead", "title" => "Where Bluebirds Fly"},
    # The Eraser
    %{"artist" => "Thom Yorke", "title" => "The Eraser"},
    %{"artist" => "Thom Yorke", "title" => "Analyse"},
    %{"artist" => "Thom Yorke", "title" => "The Clock"},
    %{"artist" => "Thom Yorke", "title" => "Black Swan"},
    %{"artist" => "Thom Yorke", "title" => "Skip Divided"},
    %{"artist" => "Thom Yorke", "title" => "Atoms for Peace"},
    %{"artist" => "Thom Yorke", "title" => "And It Rained All Night"},
    %{"artist" => "Thom Yorke", "title" => "Harrowdown Hill"},
    %{"artist" => "Thom Yorke", "title" => "Cymbal Rush"},
    # Pre-In Rainbows
    %{"artist" => "Radiohead", "title" => "I Want None of This"},
    # In Rainbows
    %{"artist" => "Radiohead", "title" => "15 Step"},
    %{"artist" => "Radiohead", "title" => "Bodysnatchers"},
    %{"artist" => "Radiohead", "title" => "Nude"},
    %{"artist" => "Radiohead", "title" => "Weird Fishes%2F Arpeggi"},
    %{"artist" => "Radiohead", "title" => "All I Need"},
    %{"artist" => "Radiohead", "title" => "Faust Arp"},
    %{"artist" => "Radiohead", "title" => "Reckoner"},
    %{"artist" => "Radiohead", "title" => "House of Cards"},
    %{"artist" => "Radiohead", "title" => "Jigsaw Falling into Place"},
    %{"artist" => "Radiohead", "title" => "Videotape"},
    # In Rainbows Disk 2
    %{"artist" => "Radiohead", "title" => "MK 1"},
    %{"artist" => "Radiohead", "title" => "Down Is the New Up"},
    %{"artist" => "Radiohead", "title" => "Go Slowly"},
    %{"artist" => "Radiohead", "title" => "MK 2"},
    %{"artist" => "Radiohead", "title" => "Last Flowers"},
    %{"artist" => "Radiohead", "title" => "Up on the Ladder"},
    %{"artist" => "Radiohead", "title" => "Bangers + Mash"},
    %{"artist" => "Radiohead", "title" => "4 Minute Warning"},
    # These Are My Twisted Words
    %{"artist" => "Radiohead", "title" => "These Are My Twisted Words"},
    # The King of Limbs
    %{"artist" => "Radiohead", "title" => "Bloom"},
    %{"artist" => "Radiohead", "title" => "Morning Mr Magpie"},
    %{"artist" => "Radiohead", "title" => "Little by Little"},
    %{"artist" => "Radiohead", "title" => "Feral"},
    %{"artist" => "Radiohead", "title" => "Lotus Flower"},
    %{"artist" => "Radiohead", "title" => "Codex"},
    %{"artist" => "Radiohead", "title" => "Give Up the Ghost"},
    %{"artist" => "Radiohead", "title" => "Separator"},
    # The Daily Mail / Staircase
    %{"artist" => "Radiohead", "title" => "The Daily Mail"},
    %{"artist" => "Radiohead", "title" => "Staircase"},
    # AMOK
    %{"artist" => "Atoms for Peace", "title" => "Before Your Very Eyes..."},
    %{"artist" => "Atoms for Peace", "title" => "Default"},
    %{"artist" => "Atoms for Peace", "title" => "Ingenue"},
    %{"artist" => "Atoms for Peace", "title" => "Dropped"},
    %{"artist" => "Atoms for Peace", "title" => "Unless"},
    %{"artist" => "Atoms for Peace", "title" => "Stuck Together Pieces"},
    %{"artist" => "Atoms for Peace", "title" => "Judge, Jury and Executioner"},
    %{"artist" => "Atoms for Peace", "title" => "Reverse Running"},
    %{"artist" => "Atoms for Peace", "title" => "Amok"},
    # Ill Wind
    %{"artist" => "Radiohead", "title" => "Ill Wind"},
    # A Moon Shaped Pool
    %{"artist" => "Radiohead", "title" => "Burn the Witch"},
    %{"artist" => "Radiohead", "title" => "Daydreaming"},
    %{"artist" => "Radiohead", "title" => "Decks Dark"},
    %{"artist" => "Radiohead", "title" => "Desert Island Disk"},
    %{"artist" => "Radiohead", "title" => "Ful Stop"},
    %{"artist" => "Radiohead", "title" => "Glass Eyes"},
    %{"artist" => "Radiohead", "title" => "Identikit"},
    %{"artist" => "Radiohead", "title" => "The Numbers"},
    %{"artist" => "Radiohead", "title" => "Present Tense"},
    %{
      "artist" => "Radiohead",
      "title" => "Tinker Tailor Soldier Sailor Rich Man Poor Man Beggar Man Thief"
    },
    %{"artist" => "Radiohead", "title" => "True Love Waits"},
    # Harry Patch (In Memory Of), Supercollider / The Butcher
    %{"artist" => "Radiohead", "title" => "Harry Patch (In Memory Of)"},
    %{"artist" => "Radiohead", "title" => "Supercollider"},
    %{"artist" => "Radiohead", "title" => "The Butcher"},
    # OK Computer OKNOTOK 1997 2017
    %{"artist" => "Radiohead", "title" => "I Promise"},
    %{"artist" => "Radiohead", "title" => "Man of War"},
    %{"artist" => "Radiohead", "title" => "Lift"},
    # KID A MNESIA
    %{"artist" => "Radiohead", "title" => "If You Say the Word"},
    %{"artist" => "Radiohead", "title" => "Follow Me Around"},
    # Suspiria
    %{"artist" => "Thom Yorke", "title" => "Suspirium"},
    %{"artist" => "Thom Yorke", "title" => "Has Ended"},
    %{"artist" => "Thom Yorke", "title" => "Open Again"},
    %{"artist" => "Thom Yorke", "title" => "Unmade"},
    # ANIMA
    %{"artist" => "Thom Yorke", "title" => "Traffic"},
    %{"artist" => "Thom Yorke", "title" => "Last I Heard (...He Was Circling the Drain)"},
    %{"artist" => "Thom Yorke", "title" => "Twist"},
    %{"artist" => "Thom Yorke", "title" => "Dawn Chorus"},
    %{"artist" => "Thom Yorke", "title" => "I Am a Very Rude Person"},
    %{"artist" => "Thom Yorke", "title" => "Not the News"},
    %{"artist" => "Thom Yorke", "title" => "The Axe"},
    %{"artist" => "Thom Yorke", "title" => "Impossible Knots"},
    %{"artist" => "Thom Yorke", "title" => "Runwayaway"},
    # A Light for Attracting Attention
    %{"artist" => "The Smile", "title" => "The Same"},
    %{"artist" => "The Smile", "title" => "The Opposite"},
    %{"artist" => "The Smile", "title" => "You Will Never Work in Television Again"},
    %{"artist" => "The Smile", "title" => "Pana-vision"},
    %{"artist" => "The Smile", "title" => "The Smoke"},
    %{"artist" => "The Smile", "title" => "Speech Bubbles"},
    %{"artist" => "The Smile", "title" => "Thin Thing"},
    %{"artist" => "The Smile", "title" => "Open The Floodgates"},
    %{"artist" => "The Smile", "title" => "Free in the Knowledge"},
    %{"artist" => "The Smile", "title" => "A Hairdryer"},
    %{"artist" => "The Smile", "title" => "Waving a White Flag"},
    %{"artist" => "The Smile", "title" => "We Don't Know What Tomorrow Brings"},
    %{"artist" => "The Smile", "title" => "Skrting on the Surface"},
    # Wall of Eyes
    %{"artist" => "The Smile", "title" => "Wall of Eyes"},
    %{"artist" => "The Smile", "title" => "Teleharmonic"},
    %{"artist" => "The Smile", "title" => "Read The Room"},
    %{"artist" => "The Smile", "title" => "Under Our Pillows"},
    %{"artist" => "The Smile", "title" => "Friend of a Friend"},
    %{"artist" => "The Smile", "title" => "I quit"},
    %{"artist" => "The Smile", "title" => "Bending Hectic"},
    %{"artist" => "The Smile", "title" => "You Know me!"}
  ]
  def songs_db do
    @songs_db
  end
end
